### ISSUE TITLE
The math formula can not render

### ISSUE THREAD

**Issue by hanqing0521** [marc0l92/joplin-plugin-plantUML#3]
This plug is wonderful, thank you for this awesome work. I meet a problem, the latex or math can not render, such as 
```PlantUML
@startuml
skinparam handwritten true
:<math>int_0^1f(x)dx</math>;
:<math>x^2+y_1+z_12^34</math>;
note right
Try also
<math>d/dxf(x)=lim_(h->0)(f(x+h)-f(x))/h</math>
<latex>P(y|\mathbf{x}) \mbox{ or } f(\mathbf{x})+\epsilon</latex>
end note
@enduml
```
just show a normal text, Thanks!

**Comment by hanqing0521** [comment]
I find that the plantuml in VSCode have the same problem, however, it provides a optional that one can  select the plantuml.jar file to render the picture.

**Comment by marc0l92** [comment]
The plantuml server is able to parse math functions only if it is working in PNG mode.

* [PNG Mode](https://www.plantuml.com/plantuml/png/FKv93eCW5Drp2k8AGen3kshLU8GkkfPeq4B2q01DeEdXArMxU_F_lVEZzIybmQLHe-UTq9wMGxMWW5beYfzsFSmmr2JIYhnfLG-dyz_Mni_GYWVtu6uZ7AKpO6kmWeMqrKgXAE9vLsAqSi9ndcHSy7rapzzG_4nJ5Z8CZOKBsZ2Pdqv8eu_ih1bCDq6_elJy5m00)
* [SVG Mode](https://www.plantuml.com/plantuml/svg/FKv93eCW5Drp2k8AGen3kshLU8GkkfPeq4B2q01DeEdXArMxU_F_lVEZzIybmQLHe-UTq9wMGxMWW5beYfzsFSmmr2JIYhnfLG-dyz_Mni_GYWVtu6uZ7AKpO6kmWeMqrKgXAE9vLsAqSi9ndcHSy7rapzzG_4nJ5Z8CZOKBsZ2Pdqv8eu_ih1bCDq6_elJy5m00)

In Joplin select the PNG mode from the plugin settings
![image](https://user-images.githubusercontent.com/12623073/145483057-8925e51c-5bca-46b0-ab9d-af15eb133b80.png)

Then you will be able to render math functions:
![image](https://user-images.githubusercontent.com/12623073/145483135-e78cd874-972a-405f-adfa-4b4ad27c09be.png)

**Comment by hanqing0521** [comment]
Thank you, I got it.
