### ISSUE TITLE
Allow configuration of a theme

### ISSUE THREAD

**Issue by mdeweerd** [marc0l92/joplin-plugin-plantUML#5]
Feature request:
Allow specifying an external theme, or integrate some themes such as the following Dark Theme:

https://github.com/ptrkcsk/one-dark-plantuml-theme/blob/main/theme.puml

**Comment by mdeweerd** [comment]
I discovered that there is an option available under "Tools>Options>PlantUML>Diagram: Header file" .

And also that Plantuml has a new directive "!theme" and that includes several themes.

**Comment by marc0l92** [comment]
The Header file function has been requested with the issue #1 to allow using default theme for all diagrams.
