### ISSUE TITLE
Rendered diagrams just became unreadable on Ubuntu

### ISSUE THREAD

**Issue by kdopen** [marc0l92/joplin-plugin-plantUML#8]
![darkuml](https://user-images.githubusercontent.com/1542228/154127976-2ec50c79-4226-4701-befe-7ad2fbffd3e7.png)
My rendered diagrams just switched to white on black for the classes/entities with gray relationships and annotations. Basically unreadable

I have no skinparams in my plantuml blocks, and am running Jopllin on Ubuntu 20.04

```
Joplin 2.6.10 (prod, linux)

Client ID: d54f2cb58b8d42b4991b1d74f66d01bc
Sync Version: 3
Profile Version: 41
Keychain Supported: No

Revision: 98fba37

```
I have the notebook synch'd via dropbox and am not seeing the same issue on MacOS

**Comment by kdopen** [comment]
And it has now fixed itself after several reboots

**Comment by marc0l92** [comment]
The default settings is to let the official plantuml server to render the diagram.
Apparently they just changed their default theme with something new that is not working very well.

If you go in the official editor:
https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
you can see that the diagram is not yellowish anymore

And, if you try to view the diagram as svg, you will see it a bit broken:
https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiX8pSd9vt98pKi1IW80

Try to use a different server by changing the plugin options.
Or choose a different theme: https://the-lum.github.io/puml-themes-gallery
Or wait until the fix this new buggy theme.
